# Dependencies
# markdown:         redcarpet
markdown: kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            A Blog Project
tagline:          Using and editing a Jekyll theme
description:      "From class to real life"
url:              NimBreitenfeld.github.io
baseurl:          /

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

# Gems
gems: [jekyll-paginate, jekyll-gist]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karloespiritu/blackdoc
