# Dependencies
# markdown:         redcarpet
markdown: kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            INLS 161 Website Project
tagline:          Using and editing a Jekyll theme
description:      "A blog project in the making"
url:              NimBreitenfeld.github.io
baseurl:          /

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karloespiritu/blackdoc
